export const PATH = {
    ROOT: '/',
    MAIN: '/main',
    NOT_FOUND: '*',
    FEEDBACKS: '/feedbacks',
    CALENDAR: '/calendar',
    PROFILE: '/profile',
    SETTINGS: '/settings',
    TRAINING: '/training',
    ACHIEVEMENTS: '/achievements',
    AUTH: '/auth',
    REGISTER: '/auth/registration',
    CONFIRM_EMAIL: '/auth/confirm-email',
    CHANGE_PASSWORD: '/auth/change-password',
    RESULT: '/result/:status',
    ERROR_LOGIN: '/result/error-login',
    ERROR_USER_EXIST: '/result/error-user-exist',
    ERROR: '/result/error',
    SUCCESS: '/result/success',
    ERROR_CHECK_EMAIL_NO_EXIST: '/result/error-check-email-no-exist',
    ERROR_CHECK_EMAIL: '/result/error-check-email',
    ERROR_CHANGE_PASSWORD: '/result/error-change-password',
    SUCCESS_CHANGE_PASSWORD: '/result/success-change-password',
};
